Services/api integration
MihlaliMgwebi/Flight-Tracker-App pull request #6
Opened 2023-02-22 03:02 UTC by MihlaliMgwebi

- [ ] Converted network request promises to Observables in api.js: the observable retrieves flight details from API.
- [ ] Cleaned up any subscriptions using observer.complete()
- [ ] Made use of RxJS to pipe observables: 
1. pipe used to chain the map operator onto the observable.
2. flight details are mapped to an object that I manipulate in dom.js

2023-02-22 03:11 UTC, MihlaliMgwebi commented
Please make any branching and folder structure suggestions too when it comes to seperation of concerns regarding my observable

2023-02-22 05:24 UTC, CharelMarais commented on api.js
> +      .then((responseJSON) =>
Is this not still a promise within an observable that should be just an observable?

2023-02-22 05:28 UTC, CharelMarais reviewed
Looks good, just have a query about the promise noted in the comments.

2023-02-23 03:47 UTC, MihlaliMgwebi commented on api.js
> +      .then((responseJSON) =>
As advised, I have used from Fetch.

2023-02-23 05:32 UTC, CharelMarais requested changes
Looks good other that the comments.

2023-02-23 05:32 UTC, CharelMarais commented on main.js
> +// import { getFirst20FlightDetails } from "./api.js";
just remove the commented code

2023-02-23 05:32 UTC, CharelMarais commented on api.js
>  // [API Calls](https://openskynetwork.github.io/opensky-api/rest.html#all-state-vectors)
Remove unused code comment

2023-02-23 05:36 UTC, MihlaliMgwebi commented on api.js
>  // [API Calls](https://openskynetwork.github.io/opensky-api/rest.html#all-state-vectors)
Removed and merging.

2023-02-23 05:36 UTC, merged